CREATE DATABASE IF NOT EXISTS moviequiz4;

CREATE TABLE IF NOT EXISTS moviequiz4.users (
  id TiNYINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(30),
  apellido VARCHAR(30),
  correo VARCHAR(50),
  contrasena VARCHAR(50)
);